### ISSUE TITLE
zc158 Compatibility, overall changes required

### ISSUE THREAD

**Issue by lat9** [lat9/ZCA-Bootstrap-Template#134]
This issue will identify changes needed for the Bootstrap-4 template to support both zc157 and the upcoming zc158 core.  This list will be added to as I discover additional changes required.

Note: Items prefixed by _*_ will also break other templates.

- [x] * `advanced_search` and `advance_search_results` pages become `search` and `search_results`, respectively.  Affects `tpl_page_not_found_default.php`, `tpl_site_map_default.php` as well as the two search-related sideboxes, too.
- [x] `about_us` page added.  No change required.
- [x] `brands` page added.  Requires template and sidebox formatting.
- [x] Include zc158-formatted language file for the common bootstrap definitions.
- [x] * zen_get_categories_name. Use zen_get_category_name() instead
- [x] * `checkout_address_book` module now returns an array of address-information instead of a set of database fields.  requires template re-formatting.
- [x] zca_get_language_file needs to account for zc158 language-file names.  Affects modalboxes templates for `info_shopping_cart`, `coupon_help` and `cvv_help`.
- [x] * `gv_faq` page changes that affect the template.
- [x] * `strftime` usage deprecated for PHP 8.1, now available `zcDate` class.
- [x] `ot_coupon` refactored, with notifier added for the one current override section.
- [x] * shipping-estimator changes
- [x] Country/zones javascript consolidation, see [this](https://github.com/zencart/zencart/issues/4488) base zencart issue.
- [x] Various sideboxes' adding 'Go' button instead of auto-submit on change; see [this](https://github.com/zencart/zencart/issues/4879) base Zen Cart issue for details.  Note: The change will be available only for zc158 and later; now using the base Zen Cart sidebox formatting.
- [x] * `checkout_confirmation` page changes for credit-covers
- [x] * 'BOX_SHOPPING_CART_DIVIDER' and 'QUANTITY_SUFFIX' no longer exist, use 'CART_QUANTITY_SUFFIX' instead.  Affects the shopping-cart sidebox and the `account_history_info` page's template.
- [x] Strip 'core' `<label></label>` tags from sidebox titles so that the core versions can be used (search, music_genres and record_companies). 
- [x] Various templates replace `zen_not_null` with `!empty`.
- [x] `account_history` now uses the `Customer` class to return a customer's order-history and breaks (see below).
- [x] `tpl_account_history_info_default.php` refactored, needs check
- [x] `tpl_account_password_default.php` adds autocomplete="current-password" to and "new-password" to password fields.
- [x] `tpl_address_book_default.php` replaces use of `zen_count_customer_address_book_entries` with `$addressArray`.
- [x] * `tpl_ask_a_question_default.php` now uses 'ENTRY_TELEPHONE_NUMBER' instead of 'ENTRY_TELEPHONE'.
- [x] * `tpl_checkout_shipping_default.php` now uses 'HEADING_SHIPPING_METHOD' instead of 'TABLE_HEADING_SHIPPING_METHOD'.
- [x] `tpl_checkout_payment_default.php` now uses 'HEADING_PAYMENT_METHOD' instead of 'TABLE_HEADING_PAYMENT_METHOD'.
- [x] * `tpl_contact_us_default.php` changes based on header change, used 'ENTRY_TELEPHONE_NUMBER' instead of 'ENTRY_TELEPHONE'.  This is going to result in PHP warnings/errors for all pre-existing templates!
- [x] `tpl_discount_coupon_default.php` now autofocuses on the coupon lookup field.
- [x] * `tpl_index_categories.php` now uses 'HEADING_TITLE_NESTED' instead of 'HEADING_TITLE'.
- [x] * `tpl_gv_send_default.php` now uses 'ENTRY_RECIPIENT_NAME' instead of 'ENTRY_NAME'.
- [x] `tpl_login_default.php` sets email fields as `autocomplete="username"` and password fields as `autocomplete="current-password"`.
- [x] * `tpl_modules_products_featured_listing.php` now uses 'TEXT_DATE_ADDED_LISTING' instead of 'TEXT_DATE_ADDED'.  Noting that this template is not used by the Bootstrap template, see #135.
- [x] `tpl_modules_products_new_listing.php` now uses the `ProductConfigurationSwitch` class.  Not used for Bootstrap, see #135.
- [x] `tpl_password_forgotten_default.php` now sets the email address autocomplete="username"
- [x] `tpl_unsubscribe_default.php` now redirects via 'SSL' instead of 'NONSSL'.

**Comment by lat9** [comment]
Noting that the template's override of the **core** `/includes/modules/shipping_estimator.php` introduces a slight wonkiness in the state-label display on zc157 when a country doesn't have zones:

![image](https://user-images.githubusercontent.com/2685585/180041025-0486f6a4-e545-4d75-b136-5b39a82f016f.png)

To prevent that, zc157-based stores can keep the previous template-override file.  For zc158, the label's aligned properly albeit with additional whitespace above:

![image](https://user-images.githubusercontent.com/2685585/180041348-b0662b0d-8024-4abb-a9fb-7459aa22fc51.png)

**Comment by lat9** [comment]
The `account_history` page now 'hides' the SQL used to gather the customer's previous orders (see [this](https://github.com/zencart/zencart/issues/5042) zc158 issue) and results in a set of warning/error logs:

```
[22-Jul-2022 14:41:31 America/New_York] Request URI: /zc158/index.php?main_page=account_history, IP address: 127.0.0.1
#0 C:\xampp\htdocs\zc158\includes\modules\pages\account_history\header_php_account_history_zca_bootstrap.php(6): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\index.php(35): require('C:\\xampp\\htdocs...')
--> PHP Warning: Undefined variable $history_query_raw in C:\xampp\htdocs\zc158\includes\modules\pages\account_history\header_php_account_history_zca_bootstrap.php on line 6.

[22-Jul-2022 14:41:31 America/New_York] Request URI: /zc158/index.php?main_page=account_history, IP address: 127.0.0.1
#0 [internal function]: zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\includes\classes\db\mysql\query_factory.php(665): trigger_error()
#2 C:\xampp\htdocs\zc158\includes\classes\db\mysql\query_factory.php(632): queryFactory->show_error()
#3 C:\xampp\htdocs\zc158\includes\classes\db\mysql\query_factory.php(273): queryFactory->set_error()
#4 C:\xampp\htdocs\zc158\includes\modules\pages\account_history\header_php_account_history_zca_bootstrap.php(7): queryFactory->Execute()
#5 C:\xampp\htdocs\zc158\index.php(35): require('C:\\xampp\\htdocs...')
--> PHP Fatal error: 1064:You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LIMIT 10' at line 1 ::  LIMIT 10 ==> (as called by) C:\xampp\htdocs\zc158\includes\modules\pages\account_history\header_php_account_history_zca_bootstrap.php on line 7 <== in C:\xampp\htdocs\zc158\includes\classes\db\mysql\query_factory.php on line 665.
```

since the template's addition to the `account_history` page 'expects' that raw SQL to be available.

**Comment by scottcwilson** [comment]
Please let me know what you think from this list should be added to 
https://docs.zen-cart.com/user/upgrading/release_specific_upgrade_considerations/

(This is for breaking changes only.)

I would add the following: 

- advanced_search and advance_search_results pages become search and search_results
- checkout_address_book module now returns an array of address-information

others?

**Comment by lat9** [comment]
I've added a prefixed * to items that will break other templates, too.  Many of them are the renaming of language constants so that previous templates are met with a PHP error for the missing definition.
